### ISSUE TITLE
Informazioni non aggiornate

### ISSUE THREAD

**Issue by EmAnzi3** [gpirrotta/protezionecivilepop#9]
Salve a tutti,
Volevo implementare sul mio Home Assistant le allerte diramate dalla Protezione Civile, tuttavia, seguendo le istruzioni presenti su Home-Assistant-custom-components-DPC-Alert non riesco ad ottenere alcuna card e i json data non sono aggiornati (sempre safe anche quando non lo dovrebbero essere) oppure dissimili da quelle fornite dal sito della PC.
La configurazione adottata è la seguente:
```
binary_sensor:
  - platform: dpc
    name: DPC Massarosa
    istat: '046018'
    alert: 'gialla'
    warnings:
      - temporali_oggi
      - idraulico_oggi
      - idrogeologico_oggi
      - temporali_domani
      - idraulico_domani
      - idrogeologico_domani
```
